name: Test

on:
  pull_request:
    paths:
      - '.github/**'
      - 'src/**'
      - 'package*.json'
      - 'action.yaml'
  workflow_dispatch:

jobs:
  build:
    name: Bundle dist/index.cjs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Semantic release
        id: release
        uses: stairwaytowonderland/node-semantic-release@main
        with:
          build-only: true
          typecheck: true
